version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'main'
    schedule:
      interval: 'daily'
      time: '9:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10

    groups:
      react:
        patterns:
          - react
          - react-dom

      storybook:
        patterns:
          - storybook
          - '@storybook/*'
          - 'storybook-addon'

      production-dependencies-minor:
        dependency-type: 'production'
        update-types:
          - 'minor'

      production-dependencies-patch:
        dependency-type: 'production'
        update-types:
          - 'patch'

      development-dependencies-minor:
        dependency-type: 'development'
        update-types:
          - 'minor'

      development-dependencies-patch:
        dependency-type: 'development'
        update-types:
          - 'patch'
