version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
      time: '10:40'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 2
    reviewers:
      - 'strozw'
      - 'jytsang'
      - 'yambal'
      - 'hasegawamayu-bc'
      - 'kawase-daiki'
    labels:
      - 'dependabot'
      - 'PR-技術レビュー'
    ignore:
      # major version update を除外
      - dependency-name: '*'
        update-types:
          - version-update:semver-major

    groups:
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
        update-types:
          - 'minor'
          - 'patch'
      storybook:
        patterns:
          - storybook
          - '@storybook/*'
          - 'storybook-addon'
        update-types:
          - 'minor'
          - 'patch'

